#include "VehicleMovementController.h"

const int JOYSTICK_Y_PIN = 9;
const int FORWARD_THRESHOLD = 600;
const int REVERSE_THRESHOLD = 600;
const int FORWARD_RELAY_PIN = 3;
const int REVERSE_RELAY_PIN = 4;
const int FRONT_RANGEFINDER_TRIGGER_PIN = 10;
const int FRONT_RANGEFINDER_ECHO_PIN = 10;
const int BACK_RANGEFINDER_TRIGGER_PIN = 2;
const int BACK_RANGEFINDER_ECHO_PIN = 1;
const int ANTI_PLUG_DELAY = 1000;
const int BUZZER_PIN = 10;
const int BUZZER_DISTANCE = 10;
const int STOP_DISTANCE = 80;

VehicleMovementController vehicle(JOYSTICK_Y_PIN, FORWARD_THRESHOLD, REVERSE_THRESHOLD, FORWARD_RELAY_PIN, REVERSE_RELAY_PIN, FRONT_RANGEFINDER_TRIGGER_PIN, FRONT_RANGEFINDER_ECHO_PIN, BACK_RANGEFINDER_TRIGGER_PIN, BACK_RANGEFINDER_ECHO_PIN, ANTI_PLUG_DELAY, BUZZER_PIN, BUZZER_DISTANCE, STOP_DISTANCE);

void setup() {

}

void loop() {
  int mille = millis();
  vehicle.update(mille);
}
